name: SpigotExtender
version: ${project.version}
main: com.king_hector.SpigotExtender.SpigotExtender
api-version: 1.18
depend: [SpigotExtender]
authors: [King_Hector]
description: '${project.description}'