name: SpigotExtender
description: Minecraft library/plugin that extends SpigotAPI with some useful methods.
main: com.king_hector.SpigotExtender.SpigotExtender
author: King_Hector
version: 1.4
api-version: 1.18